import type { Metadata } from 'next'
import '@/styles/globals.css'
import { Inter } from 'next/font/google'

import GlassPane from "@/components/GlassPane"
import SideBar from '@/components/SideBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const AuthRootLayout: React.FC = ({ children }) => {
    return (
        <html lang="en">
           
                <body className="h-screen w-screen candy-mesh p-6">
                    <GlassPane className='w-full h-full items-center '>
                        <SideBar />
                        {children}
                    </GlassPane>
                </body>
           

        </html>

    )
}

export default AuthRootLayout